parameters:
  working_directory:
    description: "directory in which a project.clj is located"
    default: "."
    type: "string"
docker:
  - image: circleci/clojure:lein-2.8.1

working_directory: ~/repo

environment:
  LEIN_ROOT: "true"
  # Customize the JVM maximum heap limit
  JVM_OPTS: -Xmx3200m
steps:
  - checkout
  - brave/dependencies:
      working_directory: << parameters.working_directory >>
  - brave/test:
      working_directory: << parameters.working_directory >>
