parameters:
  working_directory:
    description: "directory in which a project.clj is located"
    default: "."
    type: "string"
executor: brave/lein
steps:
  - checkout
  - brave/dependencies:
      working_directory: << parameters.working_directory >>
  - brave/test:
      working_directory: << parameters.working_directory >>
