# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
workflows:
  version: 2
  build-chapter-8-exercise-1:
    jobs:
      - brave/continuously_integrate
          name: "chapter-8/exercise-1"
          working_directory: "chapter-8/exercise-1"

  build-chapter-8-exercise-2:
    jobs:
      - brave/continuously_integrate
          name: "chapter-8/exercise-2"
          working_directory: "chapter-8/exercise-2"

  build-chapter-8-exercise-3:
    jobs:
      - brave/continuously_integrate
          name: "chapter-8/exercise-3"
          working_directory: "chapter-8/exercise-3"
